import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD. See the src/ folder for the source code.
*/
`;

const mode = process.argv[2];

// `npm test`: bundle the tests into single files for Node. The plugin test runs
// src/main.ts against a fake "obsidian" module (test/obsidian-mock.ts).
if (mode === "test") {
  const common = { bundle: true, platform: "node", format: "cjs", target: "node18", logLevel: "warning" };
  await esbuild.build({ ...common, entryPoints: ["test/core.test.ts"], outfile: ".test-out/core.test.cjs" });
  await esbuild.build({
    ...common,
    entryPoints: ["test/plugin.test.ts"],
    outfile: ".test-out/plugin.test.cjs",
    alias: { obsidian: "./test/obsidian-mock.ts" },
  });
  process.exit(0);
}

const prod = mode === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
